// src/constants/menuData.js

export const allMenuItems = [{
        id: 1,
        category: "Starters",
        name: "Samosa",
        description: "Crispy pastry filled with spiced potatoes and peas.",
        price: "₹130",
        details: "Served with tamarind chutney. Vegetarian-friendly.",
        image: "/Menu/samosa.jpg",
    },
    {
        id: 2,
        category: "Mains",
        name: "Grilled Zucchini Rolls",
        description: "Tender chicken cooked in creamy tomato gravy.",
        price: "₹250",
        details: "Best served with naan or rice. Contains dairy.",
        image: "/Menu/grilledRolls.jpg",
    },
    {
        id: 3,
        category: "Mains",
        name: "Veg Kolhapuri",
        description: "Grilled paneer cubes in spicy tomato-based curry.",
        price: "₹220",
        details: "Contains dairy. A popular vegetarian option.",
        image: "/Menu/vegKolhapuri.jpg",
    },
    {
        id: 4,
        category: "Breads",
        name: "Garlic Naan",
        description: "Soft flatbread infused with garlic and butter.",
        price: "₹240",
        details: "Best paired with gravies. Contains gluten.",
        image: "/Menu/GarlicNaan.jpg",
    },
    {
        id: 5,
        category: "Rice",
        name: "Veg Biryani",
        description: "Aromatic basmati rice cooked with vegetables and spices.",
        price: "₹180",
        details: "Served with raita. Spicy and flavorful.",
        image: "/Menu/VegBiryani.jpg",
    },
    {
        id: 6,
        category: "Desserts",
        name: "Gulab Jamun",
        description: "Soft milk-solid balls soaked in sugar syrup.",
        price: "₹150",
        details: "Served warm. Contains dairy.",
        image: "/Menu/GulabJamun.jpg",
    },
    {
        id: 7,
        category: "Starters",
        name: "Paneer Tikka",
        description: "Grilled marinated paneer with capsicum and onion",
        price: "₹180",
        details: "Grilled over charcoal. Contains dairy and spices",
        image: "/Menu/PaneerTikka.jpg",
    },
    {
        id: 8,
        category: "Mains",
        name: "Veg Spring Rolls",
        description: "Crispy rolls stuffed with spiced mixed vegetables, deep-fried to golden perfection.",
        price: "₹150",
        details: "Contains gluten and cabbage. Served with sweet chili sauce. Vegan-friendly.",
        image: "/Menu/VegSpringRolls.jpg",
    },
    {
        id: 9,
        category: "Drinks",
        name: "Lemon Iced Tea",
        description: "Chilled black tea infused with lemon juice and a hint of honey for a refreshing taste.",
        price: "₹250",
        details: "Served cold with ice. Caffeine content moderate. Vegan-friendly.",
        image: "/Menu/LemonIcedTea.jpg",
    },
    {
        id: 10,
        category: "Mains",
        name: "Dal Makhni",
        description: "Slow-cooked black lentils in a rich, creamy tomato-based gravy infused with butter and Indian spices.",
        price: "₹200",
        details: "Contains dairy (butter and cream). Best enjoyed with naan or jeera rice. A Punjabi classic.",
        image: "/Menu/DalMakhni.jpg",
    },
    {
        id: 11,
        category: "Starters",
        name: "Chilli Paneer Dry",
        description: "Crispy fried paneer cubes tossed in a spicy Indo-Chinese sauce with onions, capsicum, and garlic.",
        price: "₹190",
        details: "A popular vegetarian starter. Contains dairy and soy sauce. Best served hot with dips or noodles.",
        image: "/Menu/ChilliPaneerDry.jpg",
    },
    {
        id: 12,
        category: "Mains",
        name: "Malai Kofta",
        description: "Soft cottage cheese and potato dumplings served in a rich, creamy tomato and cashew gravy.",
        price: "₹240",
        details: "Rich and indulgent North Indian delicacy. Contains dairy and nuts. Best paired with naan or jeera rice.",
        image: "/Menu/MalaiKofta.jpg",
    },
];

export const categories = [
    "All",
    "Starters",
    "Mains",
    "Breads",
    "Rice",
    "Desserts",
    "Drinks",
];